
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const OrderSide = {
  BUY: 'BUY',
  SELL: 'SELL'
} as const

export type OrderSide = (typeof OrderSide)[keyof typeof OrderSide]


export const TradeStatus = {
  PLANNED: 'PLANNED',
  OPEN: 'OPEN',
  PARTIALLY_CLOSED: 'PARTIALLY_CLOSED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  ERROR: 'ERROR'
} as const

export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus]


export const CloseReason = {
  TP1_HIT: 'TP1_HIT',
  TP2_HIT: 'TP2_HIT',
  SL_HIT: 'SL_HIT',
  MANUAL: 'MANUAL',
  INVALIDATED: 'INVALIDATED',
  EXPIRED: 'EXPIRED',
  ERROR: 'ERROR',
  CLOSED_WHILE_DOWN: 'CLOSED_WHILE_DOWN'
} as const

export type CloseReason = (typeof CloseReason)[keyof typeof CloseReason]
